### ISSUE TITLE
should depend on sphinx

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/anarchy_sphinx#1]
After installing `anarchy-sphinx` from pip, get this error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/anarchysphinx", line 9, in <module>
    load_entry_point('anarchy-sphinx==0.3.1', 'console_scripts', 'anarchysphinx')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/swift_domain/__init__.py", line 1, in <module>
    from .swift import *
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/swift_domain/swift.py", line 17, in <module>
    from sphinx import addnodes
ImportError: cannot import name 'addnodes'
```

this is because sphinx is not installed; it should be a dependency of anarchy_sphinx

**Comment by dunkelstern** [comment]
Oh wow, good catch, i'll update the setup.py and republish
